### ISSUE TITLE
Stuck on ./runYOLO

### ISSUE THREAD

**Issue by BigfanofGreenDay** [AmeyaWagh/Traffic_sign_detection_YOLO#2]
I ran it on Raspberry PI 3b. Previous steps are fine, but I stuck on "./runYOLO". I tried "sudo ./runYOLO", but still the same:

{'dataset': '/home/pi/Traffic_sign_detection_YOLO/dataset', 'yoloConfig': {'metaLoad': '/home/pi/Traffic_sign_detection_YOLO/darkflow/built_graph/tiny-yolo-voc27.meta', 'threshold': 0.01, 'pbLoad': '/home/pi/Traffic_sign_detection_YOLO/darkflow/built_graph/tiny-yolo-voc27.pb', 'gpu': 0.0, 'labels': '../labels.txt'}}

Loading from .pb and .meta
Traceback (most recent call last):
  File "YOLOtest.py", line 126, in <module>
    det = objectDetector(video=False)
  File "YOLOtest.py", line 21, in __init__
    self.tfnet = TFNet(self.options)
  File "/home/pi/Traffic_sign_detection_YOLO/darkflow/darkflow/net/build.py", line 54, in __init__
    self.build_from_pb()
  File "/home/pi/Traffic_sign_detection_YOLO/darkflow/darkflow/net/build.py", line 87, in build_from_pb
    name=""
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: 'RealDiv'

Please help me, thx

**Comment by AmeyaWagh** [comment]
What version of tensorflow are you using?. 
```python
import tensorflow as tf
tf.__version__
```

```bash
>>> import tensorflow as tf
>>> tf.__version__
'1.13.1'
>>> 
```
Also check if your python is pointed to python3 interpreter
